#!/usr/bin/env sh
set -e

# ===========================
# Usage:
# ./octopus [TAG|latest] [OUTPUT_PATH] [GITHUB_TOKEN]
#
# TAG: optional, GitHub release tag (default: latest)
# OUTPUT_PATH: optional, default './octopus.jar'
# ===========================

TAG="${1:-latest}"
OUTPUT="${2:-./cheetah.jar}"
REPO="o7studios/octopus-plugin"
ASSET_PATTERN="octopus-all.jar"

# Call the parent 'github' script
github "$REPO" "$ASSET_PATTERN" "$OUTPUT" "$TAG"
